---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:18-alpine
  commands: ["npm ci"]

- name: npm-ls
  image: node:18-alpine
  commands: ["npm ls"]

- name: test-node-18
  image: node:18-alpine
  commands: ["npm run test -s"]

- name: test-node-20
  image: node:20-alpine
  commands: ["npm run test -s"]

- name: publish
  image: livingdocs/semantic-release:v2.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 5767d206bf6ea0ac2239efa61323f1a28800d3d299d433048971c05def233b14

...
