---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:8-alpine
  commands: ["npm install"]

- name: npm-ls
  image: node:8-alpine
  commands: ["npm ls"]

- name: test-node-8
  image: node:8-alpine
  commands: ["npm run test -s"]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: ac531211552345c14a7f9acef077dba96d0f9602d8c298a0f1f779797cf0237e

...
