---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: node:12-alpine
  commands: ["npm install"]

- name: npm-ls
  image: node:12-alpine
  commands: ["npm ls"]

- name: test-node-12
  image: node:12-alpine
  commands: ["npm run test -s"]

- name: test-node-14
  image: node:14-alpine
  commands: ["npm run test -s"]

- name: test-node-16
  image: node:16-alpine
  commands: ["npm run test -s"]

- name: publish
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: e92a4f0cfab57ba83f4ec6ea13942fd05ee13530e140df95031407cf9543949a

...
